### ISSUE TITLE
Changing metric from bbox to segm

### ISSUE THREAD

**Issue by tobi-park** [IDEACVR/DINO#56]
Hi,

How can i change IoU metric from bbox to segmentation?

thx

**Comment by FengLi-ust** [comment]
You can refer to [DETR code](https://github.com/facebookresearch/detr) to see how it is evaluated when doing segmentation (when args.masks=True).

**Comment by liviazampereti** [comment]
I've changed masks to True in DINO_4scale.py, but i got this error, while training:

Traceback (most recent call last):
  File "main.py", line 398, in <module>
    main(args)
  File "main.py", line 285, in main
    args.clip_max_norm, wo_class_error=wo_class_error, lr_scheduler=lr_scheduler, args=args, logger=(logger if args.save_log else None), ema_m=ema_m)
  File "/content/DINO/engine.py", line 48, in train_one_epoch
    outputs = model(samples, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

Would I have to change annother parameter?

**Comment by liviazampereti** [comment]
I've changed the mask to True in DINO_4scale.py, and got this error:

Traceback (most recent call last):
  File "main.py", line 398, in <module>
    main(args)
  File "main.py", line 285, in main
    args.clip_max_norm, wo_class_error=wo_class_error, lr_scheduler=lr_scheduler, args=args, logger=(logger if args.save_log else None), ema_m=ema_m)
  File "/content/DINO/engine.py", line 48, in train_one_epoch
    outputs = model(samples, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

Should i change another parameter?

**Comment by SuperHenry2333** [comment]
@liviazampereti Our code does not support segmentation now. You should not change mask to True.

**Comment by sri9s** [comment]
@SuperHenry2333 How can I perform both detection as well as segmentation here?
