### ISSUE TITLE
when call the main.py in Windows, it shows the permission error related to shutil.copyfile?

### ISSUE THREAD

**Issue by AI-Passionner** [IDEACVR/DINO#79]
python main.py --output_dir logs/kv/R50-MS4 -c config/DINO/kv_4scale.py --coco_path D:/data/invoice_for_object_detection/invoice_kv_to_voc_COCO_format --options dn_scalar=100 embed_init_tgt=TRUE dn_label_coef=1.0 dn_bbox_coef=1.0 use_ema=False dn_box_noise_scale=1.0

C:\Users\xxx\anaconda3\envs\dino\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Not using distributed mode
Loading config file from config/DINO/kv_4scale.py
Traceback (most recent call last):
  File "main.py", line 395, in <module>
    main(args)
  File "main.py", line 94, in main
    cfg = SLConfig.fromfile(args.config_file)
  File "C:\Users\xxx\PycharmProjects\DINO\util\slconfig.py", line 188, in fromfile
    cfg_dict, cfg_text = SLConfig._file2dict(filename)
  File "C:\Users\xxx\PycharmProjects\DINO\util\slconfig.py", line 87, in _file2dict
    osp.join(temp_config_dir, temp_config_name))
  File "C:\Users\xxx\anaconda3\envs\dino\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpozuruu45\\tmpsgtagp3d.py'

**Comment by SuperHenry2333** [comment]
Please refer to #43 .

**Comment by AI-Passionner** [comment]
@SuperHenry2333, based on the link, adding 'temp_config_file.close()' solved the problem, quoted as "Changing the temp directory did not work for me. In the function 'def _file2dict', I added a line 'temp_config_file.close()' after 'temp_config_file = tempfile.NamedTemporaryFile(dir=temp_config_dir, suffix='.py')' and the problem was solved.

I am not sure if it is the case in Linux. But it seems a bug to me. Why not just add it in the code base so that no user will post this issue again?
